/* krate docs search UI — generated by the krate docs plugin.
 *
 * Drives the docfind WASM search module (docfind.js + docfind_bg.wasm) when it
 * was built, and falls back to the JSON index (docs/data/search-index.json)
 * otherwise. All event handling is delegated to `document` so the widget keeps
 * working across SPA page transitions.
 */
(function () {
    "use strict";

    var SEARCH_BASE = "/docs/search/";
    var INDEX_JSON = "/docs/data/search-index.json";
    var MAX_RESULTS = 8;

    var trigger = null;
    var backdrop = null;
    var dialog = null;
    var input = null;
    var resultsEl = null;

    var engine = null;
    var jsonIndex = null;
    var enginePromise = null;
    var timer = null;
    var activeIndex = -1;
    var items = [];

    function bind() {
        trigger = document.getElementById("krate-search-trigger");
        backdrop = document.getElementById("krate-search-backdrop");
        dialog = document.getElementById("krate-search-dialog");
        input = document.getElementById("krate-search-input");
        resultsEl = document.getElementById("krate-search-results");
        return !!(trigger && dialog && input && resultsEl);
    }

    function esc(value) {
        return String(value).replace(/[&<>"']/g, function (c) {
            return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
        });
    }

    function setState(state, message) {
        if (!bind()) return;
        resultsEl.innerHTML = '<div class="krate-search-state" data-state="' + esc(state) + '">' + esc(message) + "</div>";
        items = [];
        activeIndex = -1;
    }

    function open() {
        if (!bind()) return;
        dialog.hidden = false;
        document.body.classList.add("krate-search-open");
        if (backdrop) backdrop.classList.add("open");
        trigger.setAttribute("aria-expanded", "true");
        window.setTimeout(function () {
            if (input) input.focus();
        }, 20);
        var q = input.value.trim();
        if (q) runSearch(q);
        else setState("idle", "Start typing to search the documentation");
    }

    function close() {
        if (!bind()) return;
        dialog.hidden = true;
        document.body.classList.remove("krate-search-open");
        if (backdrop) backdrop.classList.remove("open");
        trigger.setAttribute("aria-expanded", "false");
    }

    function loadEngine() {
        if (enginePromise) return enginePromise;
        enginePromise = import(SEARCH_BASE + "docfind.js")
            .then(function (mod) {
                engine = typeof mod.default === "function" ? mod.default : null;
                if (!engine) throw new Error("docfind module has no default export");
            })
            .catch(function () {
                engine = null;
                return fetch(INDEX_JSON)
                    .then(function (r) {
                        if (!r.ok) throw new Error("no index");
                        return r.json();
                    })
                    .then(function (idx) {
                        jsonIndex = Array.isArray(idx) ? idx : [];
                    })
                    .catch(function () {
                        jsonIndex = [];
                    });
            });
        return enginePromise;
    }

    function fallbackScore(query, entry) {
        var q = query.toLowerCase();
        var words = q.split(/\s+/).filter(Boolean);
        if (!words.length) return 0;
        var hay = (entry.title + " " + (entry.content || "")).toLowerCase();
        var titleHay = (entry.title || "").toLowerCase();
        var score = 0;
        for (var i = 0; i < words.length; i++) {
            if (hay.indexOf(words[i]) === -1) return 0;
            score += titleHay.indexOf(words[i]) !== -1 ? 10 : 1;
        }
        return score;
    }

    function searchJSON(query, max) {
        if (!jsonIndex) return [];
        return jsonIndex
            .map(function (entry) { return { entry: entry, score: fallbackScore(query, entry) }; })
            .filter(function (s) { return s.score > 0; })
            .sort(function (a, b) { return b.score - a.score; })
            .slice(0, max)
            .map(function (s) { return s.entry; });
    }

    function highlight() {
        items.forEach(function (el, i) {
            el.classList.toggle("active", i === activeIndex);
            if (i === activeIndex) el.setAttribute("aria-selected", "true");
            else el.removeAttribute("aria-selected");
        });
    }

    function renderResults(list) {
        if (!bind()) return;
        if (!list || !list.length) {
            setState("empty", "No results found");
            return;
        }
        var html = '<div class="krate-search-list" role="listbox">';
        list.forEach(function (d, i) {
            var href = d.href || d.path || "/";
            var title = esc(d.title || "Untitled");
            var category = esc(d.category || "");
            var body = esc((d.body || d.content || "").slice(0, 220));
            html += '<a class="krate-search-item" href="' + esc(href) + '" role="option" data-index="' + i + '">';
            html += '<span class="krate-search-item-top">';
            html += '<span class="krate-search-item-title">' + title + "</span>";
            if (category) html += '<span class="krate-search-item-category">' + category + "</span>";
            html += "</span>";
            if (body) html += '<span class="krate-search-item-snippet">' + body + "</span>";
            html += "</a>";
        });
        html += "</div>";
        resultsEl.innerHTML = html;
        items = Array.prototype.slice.call(resultsEl.querySelectorAll(".krate-search-item"));
        activeIndex = -1;
        highlight();
    }

    function runSearch(query) {
        if (!query) {
            setState("idle", "Start typing to search the documentation");
            return;
        }
        setState("loading", "Searching…");
        loadEngine().then(function () {
            if (input && input.value.trim() !== query) return;
            if (engine) {
                return engine(query, MAX_RESULTS)
                    .then(function (results) {
                        if (input && input.value.trim() !== query) return;
                        renderResults(results);
                    })
                    .catch(function () {
                        if (input && input.value.trim() !== query) return;
                        renderResults(searchJSON(query, MAX_RESULTS));
                    });
            }
            renderResults(searchJSON(query, MAX_RESULTS));
        });
    }

    function moveActive(delta) {
        if (!items.length) return;
        activeIndex = (activeIndex + delta + items.length) % items.length;
        highlight();
        var el = items[activeIndex];
        if (el && el.scrollIntoView) el.scrollIntoView({ block: "nearest" });
    }

    function submitActive() {
        if (activeIndex >= 0 && activeIndex < items.length) {
            window.location.href = items[activeIndex].getAttribute("href");
            close();
        }
    }

    document.addEventListener("click", function (event) {
        if (!bind()) return;
        var t = event.target;
        if (t.closest("#krate-search-trigger")) {
            if (dialog.hidden) open();
            else close();
            return;
        }
        if (t.closest("#krate-search-backdrop")) {
            close();
            return;
        }
        if (t.closest(".krate-search-item")) {
            close();
            return;
        }
    });

    document.addEventListener("input", function (event) {
        if (event.target && event.target.id === "krate-search-input") {
            if (timer) window.clearTimeout(timer);
            timer = window.setTimeout(function () {
                runSearch(input ? input.value.trim() : "");
            }, 140);
        }
    });

    document.addEventListener("keydown", function (event) {
        if (!bind()) return;
        var mod = event.ctrlKey || event.metaKey;
        if (mod && event.key.toLowerCase() === "k") {
            event.preventDefault();
            if (dialog.hidden) open();
            return;
        }
        if (dialog.hidden) return;
        if (event.key === "Escape") {
            close();
            return;
        }
        if (document.activeElement === input) {
            if (event.key === "ArrowDown") {
                event.preventDefault();
                moveActive(1);
            } else if (event.key === "ArrowUp") {
                event.preventDefault();
                moveActive(-1);
            } else if (event.key === "Enter") {
                event.preventDefault();
                submitActive();
            }
        }
    });

    window.addEventListener("krate:navigate", function () {
        close();
        if (timer) window.clearTimeout(timer);
    });
})();
