/* krate docs search UI — generated by the krate docs plugin.
 *
 * Tries the configured engine first (ENGINE): "pagefind" loads the Pagefind
 * bundle (pagefind.js + the indexed chunks), "docfind" loads the docfind WASM
 * module, and "json" reads docs/data/search-index.json. Any engine that fails
 * to load degrades to the JSON index, so search keeps working in dev, offline,
 * or when an index wasn't built. All event handling is delegated to `document`
 * so the widget keeps working across SPA page transitions.
 */
(function () {
    "use strict";

    // Idempotent: the script is re-loaded on SPA navigation. Re-binding would
    // duplicate the document/window listeners below.
    if (window.__krateSearch && window.__krateSearch.__krate) return;

    var SEARCH_BASE = "/docs/search/";
    var INDEX_JSON = "/docs/data/search-index.json";
    var PAGE_FIND_BASE = "/pagefind/";
    var MAX_RESULTS = 8;
    var ENGINE = "docfind";

    var trigger = null;
    var backdrop = null;
    var dialog = null;
    var input = null;
    var resultsEl = null;

    var mode = null;
    var docfind = null;
    var pagefind = null;
    var jsonIndex = null;
    var enginePromise = null;
    var timer = null;
    var activeIndex = -1;
    var items = [];

    function bind() {
        trigger = document.getElementById("krate-search-trigger");
        backdrop = document.getElementById("krate-search-backdrop");
        dialog = document.getElementById("krate-search-dialog");
        input = document.getElementById("krate-search-input");
        resultsEl = document.getElementById("krate-search-results");
        return !!(trigger && dialog && input && resultsEl);
    }

    function esc(value) {
        return String(value).replace(/[&<>"']/g, function (c) {
            return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
        });
    }

    function setState(state, message) {
        if (!bind()) return;
        resultsEl.innerHTML = '<div class="krate-search-state" data-state="' + esc(state) + '">' + esc(message) + "</div>";
        items = [];
        activeIndex = -1;
    }

    function open() {
        if (!bind()) return;
        dialog.hidden = false;
        document.body.classList.add("krate-search-open");
        if (backdrop) backdrop.classList.add("open");
        trigger.setAttribute("aria-expanded", "true");
        window.setTimeout(function () {
            if (input) input.focus();
        }, 20);
        var q = input.value.trim();
        if (q) runSearch(q);
        else setState("idle", "Start typing to search the documentation");
    }

    function close() {
        if (!bind()) return;
        dialog.hidden = true;
        document.body.classList.remove("krate-search-open");
        if (backdrop) backdrop.classList.remove("open");
        trigger.setAttribute("aria-expanded", "false");
    }

    function loadJSON() {
        return fetch(INDEX_JSON)
            .then(function (r) {
                if (!r.ok) throw new Error("no index");
                return r.json();
            })
            .then(function (idx) {
                jsonIndex = Array.isArray(idx) ? idx : [];
                mode = "json";
            })
            .catch(function () {
                jsonIndex = [];
                mode = "json";
            });
    }

    function loadDocfind() {
        return import(SEARCH_BASE + "docfind.js").then(function (mod) {
            if (typeof mod.default !== "function") throw new Error("docfind module has no default export");
            docfind = mod.default;
            mode = "docfind";
        });
    }

    function loadPagefind() {
        return import(PAGE_FIND_BASE + "pagefind.js").then(function (mod) {
            pagefind = mod;
            if (typeof pagefind.options === "function") {
                return pagefind.options({ basePath: PAGE_FIND_BASE });
            }
        }).then(function () {
            if (typeof pagefind.init === "function") pagefind.init();
            mode = "pagefind";
        });
    }

    // Resolve the active engine once. Prefer the configured engine, then
    // docfind, then JSON; a failed import in any step falls through.
    function loadEngine() {
        if (enginePromise) return enginePromise;
        var chain;
        if (ENGINE === "pagefind") {
            chain = loadPagefind().catch(loadDocfind).catch(loadJSON);
        } else if (ENGINE === "docfind") {
            chain = loadDocfind().catch(loadJSON);
        } else {
            chain = loadJSON();
        }
        enginePromise = chain.catch(function () {
            mode = "json";
            return loadJSON();
        });
        return enginePromise;
    }

    // Normalize a Pagefind result (already data()'d) into krate's hit shape.
    function toHit(data) {
        var meta = data.meta || {};
        return {
            href: data.url || "/",
            title: meta.title || "Untitled",
            body: data.plain_excerpt || "",
        };
    }

    function searchPagefind(query, max) {
        return pagefind.search(query).then(function (res) {
            var top = (res.results || []).slice(0, max);
            return Promise.all(top.map(function (r) { return r.data(); })).then(function (docs) {
                return docs.map(toHit);
            });
        });
    }

    function fallbackScore(query, entry) {
        var q = query.toLowerCase();
        var words = q.split(/\s+/).filter(Boolean);
        if (!words.length) return 0;
        var hay = (entry.title + " " + (entry.content || "")).toLowerCase();
        var titleHay = (entry.title || "").toLowerCase();
        var score = 0;
        for (var i = 0; i < words.length; i++) {
            if (hay.indexOf(words[i]) === -1) return 0;
            score += titleHay.indexOf(words[i]) !== -1 ? 10 : 1;
        }
        return score;
    }

    function searchJSON(query, max) {
        if (!jsonIndex) return [];
        return jsonIndex
            .map(function (entry) { return { entry: entry, score: fallbackScore(query, entry) }; })
            .filter(function (s) { return s.score > 0; })
            .sort(function (a, b) { return b.score - a.score; })
            .slice(0, max)
            .map(function (s) { return s.entry; });
    }

    function highlight() {
        items.forEach(function (el, i) {
            el.classList.toggle("active", i === activeIndex);
            if (i === activeIndex) el.setAttribute("aria-selected", "true");
            else el.removeAttribute("aria-selected");
        });
    }

    function renderResults(list) {
        if (!bind()) return;
        if (!list || !list.length) {
            setState("empty", "No results found");
            return;
        }
        var html = '<div class="krate-search-list" role="listbox">';
        list.forEach(function (d, i) {
            var href = d.href || d.path || "/";
            var title = esc(d.title || "Untitled");
            var category = esc(d.category || "");
            var body = esc((d.body || d.content || "").slice(0, 220));
            html += '<a class="krate-search-item" href="' + esc(href) + '" role="option" data-index="' + i + '">';
            html += '<span class="krate-search-item-top">';
            html += '<span class="krate-search-item-title">' + title + "</span>";
            if (category) html += '<span class="krate-search-item-category">' + category + "</span>";
            html += "</span>";
            if (body) html += '<span class="krate-search-item-snippet">' + body + "</span>";
            html += "</a>";
        });
        html += "</div>";
        resultsEl.innerHTML = html;
        items = Array.prototype.slice.call(resultsEl.querySelectorAll(".krate-search-item"));
        activeIndex = -1;
        highlight();
    }

    // Headless query: loads the engine on demand and resolves normalized hits
    // ({href,title,body,category}). Shared by the built-in widget and the
    // window.__krateSearch API so custom components render their own results.
    function queryEngine(query, max) {
        var limit = max || MAX_RESULTS;
        if (!query) return Promise.resolve([]);
        return loadEngine().then(function () {
            if (mode === "pagefind") {
                return searchPagefind(query, limit).catch(function () { return searchJSON(query, limit); });
            }
            if (mode === "docfind") {
                return Promise.resolve(docfind(query, limit)).catch(function () { return searchJSON(query, limit); });
            }
            return Promise.resolve(searchJSON(query, limit));
        });
    }

    function runSearch(query) {
        if (!query) {
            setState("idle", "Start typing to search the documentation");
            return;
        }
        setState("loading", "Searching…");
        queryEngine(query, MAX_RESULTS).then(function (results) {
            if (input && input.value.trim() !== query) return;
            renderResults(results);
        });
    }

    function moveActive(delta) {
        if (!items.length) return;
        activeIndex = (activeIndex + delta + items.length) % items.length;
        highlight();
        var el = items[activeIndex];
        if (el && el.scrollIntoView) el.scrollIntoView({ block: "nearest" });
    }

    function submitActive() {
        if (activeIndex >= 0 && activeIndex < items.length) {
            window.location.href = items[activeIndex].getAttribute("href");
            close();
        }
    }

    document.addEventListener("click", function (event) {
        if (!bind()) return;
        var t = event.target;
        if (t.closest("#krate-search-trigger")) {
            if (dialog.hidden) open();
            else close();
            return;
        }
        if (t.closest("#krate-search-backdrop")) {
            close();
            return;
        }
        if (t.closest(".krate-search-item")) {
            close();
            return;
        }
    });

    document.addEventListener("input", function (event) {
        if (event.target && event.target.id === "krate-search-input") {
            if (timer) window.clearTimeout(timer);
            timer = window.setTimeout(function () {
                runSearch(input ? input.value.trim() : "");
            }, 140);
        }
    });

    document.addEventListener("keydown", function (event) {
        if (!bind()) return;
        var mod = event.ctrlKey || event.metaKey;
        if (mod && event.key.toLowerCase() === "k") {
            event.preventDefault();
            if (dialog.hidden) open();
            return;
        }
        if (dialog.hidden) return;
        if (event.key === "Escape") {
            close();
            return;
        }
        if (document.activeElement === input) {
            if (event.key === "ArrowDown") {
                event.preventDefault();
                moveActive(1);
            } else if (event.key === "ArrowUp") {
                event.preventDefault();
                moveActive(-1);
            } else if (event.key === "Enter") {
                event.preventDefault();
                submitActive();
            }
        }
    });

    window.addEventListener("krate:navigate", function () {
        close();
        if (timer) window.clearTimeout(timer);
    });

    // ── Headless search API ────────────────────────────────────────────────
    // Custom components query the same index the built-in widget uses, with no
    // fixed markup or positioning. `search("query", { limit })` resolves to an
    // array of { href, title, body, category }.
    var api = {
        __krate: true,
        ready: function () { return loadEngine(); },
        search: function (query, opts) {
            return queryEngine(query, (opts && opts.limit) || MAX_RESULTS);
        },
        engine: function () { return mode; },
        maxResults: MAX_RESULTS,
        open: open,
        close: close,
    };
    window.__krateSearch = api;
    try {
        window.dispatchEvent(new CustomEvent("krate:search-ready", { detail: api }));
    } catch (e) {}
})();
