packages:
  - packages/*
  - examples

allowBuilds:
  '@krate/core': true
  'esbuild': true

supportedArchitectures:
  os:
    - current
    - win32
    - linux
    - darwin
  cpu:
    - current
    - x64
    - arm64
