package plugin

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/kratejs/krate/packages/compiler/internal/docs"
	"github.com/kratejs/krate/packages/compiler/internal/escape"
)

// taxonomyEntry is one tag or category with its member pages.
type taxonomyEntry struct {
	Name  string
	Slug  string
	Pages []docs.Page
}

// generateTaxonomyPages emits an index page per tag and per category under
// /docs/tags/<slug>/ and /docs/categories/<slug>/. Pages are sorted by title.
func generateTaxonomyPages(ctx *BuildHookCtx, genDir string, theme *resolvedDocsTheme, opts *DocsPluginOptions, pages []docs.Page, sections []docs.SidebarItem) error {
	tags := map[string][]docs.Page{}
	categories := map[string][]docs.Page{}
	for _, p := range pages {
		for _, t := range p.Tags {
			tags[t] = append(tags[t], p)
		}
		for _, c := range p.Categories {
			categories[c] = append(categories[c], p)
		}
	}

	emit := func(kind string, m map[string][]docs.Page) error {
		entries := make([]taxonomyEntry, 0, len(m))
		for name, ps := range m {
			sorted := append([]docs.Page(nil), ps...)
			sort.SliceStable(sorted, func(i, j int) bool { return sorted[i].Title < sorted[j].Title })
			entries = append(entries, taxonomyEntry{Name: name, Slug: slugifyName(name), Pages: sorted})
		}
		sort.Slice(entries, func(i, j int) bool { return entries[i].Name < entries[j].Name })
		for _, e := range entries {
			rel := kind + "/" + e.Slug
			tsxPath := filepath.Join(genDir, filepath.FromSlash(rel)+".tsx")
			if err := os.MkdirAll(filepath.Dir(tsxPath), 0755); err != nil {
				return err
			}
			src := buildTaxonomyTSX(theme, opts, tsxPath, kind, e, sections)
			if err := os.WriteFile(tsxPath, []byte(src), 0644); err != nil {
				return err
			}
			if ctx.GeneratedPages != nil {
				*ctx.GeneratedPages = append(*ctx.GeneratedPages, GeneratedPage{Path: tsxPath, Route: "docs/" + rel})
			}
		}
		return nil
	}

	if err := emit("tags", tags); err != nil {
		return err
	}
	return emit("categories", categories)
}

func taxonomyTitle(kind, name string) string {
	if kind == "categories" {
		return "Category: " + name
	}
	return "Tag: " + name
}

func buildTaxonomyTSX(theme *resolvedDocsTheme, opts *DocsPluginOptions, tsxPath, kind string, e taxonomyEntry, sections []docs.SidebarItem) string {
	var sb strings.Builder
	sb.WriteString("// Auto-generated by krate docs plugin (taxonomy index)\n")

	if theme != nil {
		if layoutRel := theme.importSpecifier(filepath.Dir(tsxPath)); layoutRel != "" {
			sb.WriteString(fmt.Sprintf("import DocsLayout from \"%s\";\n", layoutRel))
		}
	}
	sb.WriteString("\n")

	title := taxonomyTitle(kind, e.Name)
	titleJSON, _ := json.Marshal(title)
	siteJSON, _ := json.Marshal(opts.Title)
	currentJSON, _ := json.Marshal(kind + "/" + e.Slug)
	sidebarJSON := marshalJSONArray(sections)
	socialJSON := marshalJSONArray(opts.Links)

	sb.WriteString("export default function TaxonomyPage() {\n")
	sb.WriteString("  const docsProps = {\n")
	sb.WriteString("    pageTitle: " + string(titleJSON) + ",\n")
	sb.WriteString("    siteTitle: " + string(siteJSON) + ",\n")
	sb.WriteString("    sidebarItems: " + string(sidebarJSON) + ",\n")
	sb.WriteString("    tocItems: [],\n")
	sb.WriteString("    breadcrumbs: [],\n")
	sb.WriteString("    template: \"doc\",\n")
	sb.WriteString("    socialLinks: " + string(socialJSON) + ",\n")
	sb.WriteString("    currentPath: " + string(currentJSON) + ",\n")
	sb.WriteString("  };\n")
	sb.WriteString("  return (\n")
	sb.WriteString("    <DocsLayout {...docsProps}>\n")
	sb.WriteString("      <div class=\"md-content\">\n")
	sb.WriteString("        <h1>" + escape.HTML(title) + "</h1>\n")
	sb.WriteString("        <ul class=\"taxonomy-list\">\n")
	for _, p := range e.Pages {
		url := docs.PageURL(p.Path)
		sb.WriteString("          <li><a href=" + jsxAttrExpr(url) + ">" + escape.HTML(p.Title) + "</a></li>\n")
	}
	sb.WriteString("        </ul>\n")
	sb.WriteString("      </div>\n")
	sb.WriteString("    </DocsLayout>\n")
	sb.WriteString("  );\n")
	sb.WriteString("}\n")
	return sb.String()
}

// slugifyName lowercases and hyphenates a tag/category for use in a URL path.
func slugifyName(name string) string {
	var b strings.Builder
	prevDash := false
	for _, r := range strings.ToLower(strings.TrimSpace(name)) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
			prevDash = false
		default:
			if !prevDash && b.Len() > 0 {
				b.WriteByte('-')
				prevDash = true
			}
		}
	}
	return strings.Trim(b.String(), "-")
}
