package plugin

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"krate-compiler/internal/docfind"
	"krate-compiler/internal/docs"
	"krate-compiler/internal/plugin/searchassets"
)

// DocsSearchOptions configures the docs site search bar.
type DocsSearchOptions struct {
	// Enabled turns the search bar on/off. Default: true.
	Enabled bool `json:"enabled"`
	// Engine selects the index backend. "docfind" (default) embeds a WASM
	// search index built in-process from the docs; "json" uses the classic
	// search-index.json fallback. The client falls back to JSON automatically
	// if the WASM index is unavailable.
	Engine string `json:"engine"`
	// MaxResults caps the number of results shown. Default: 8.
	MaxResults int `json:"maxResults"`
}

// searchDir is the output sub-directory for search assets.
const searchDir = "docs/search"

// searchConfig returns the effective search options with defaults applied.
func searchConfig(opts *DocsPluginOptions) (enabled bool, engine string, maxResults int) {
	enabled = true
	engine = "docfind"
	maxResults = 8
	if opts.Search != nil {
		if !opts.Search.Enabled {
			enabled = false
		}
		if opts.Search.Engine != "" {
			engine = opts.Search.Engine
		}
		if opts.Search.MaxResults > 0 {
			maxResults = opts.Search.MaxResults
		}
	}
	return
}

// buildSearchDocuments converts docs pages into docfind index documents.
func buildSearchDocuments(pages []docs.Page) []docfind.Document {
	documents := make([]docfind.Document, 0, len(pages))
	for _, p := range pages {
		documents = append(documents, docfind.Document{
			Title:    p.Title,
			Category: p.Dir,
			Href:     docs.PageURL(p.Path),
			Body:     docs.StripHTMLTags(p.Content),
			Keywords: p.Keywords,
		})
	}
	return documents
}

// buildSearchAssets writes the search UI and (when the engine is "docfind")
// builds the in-process WASM index and writes the searchable module + JS glue.
// It returns an error only when the WASM index build fails; the caller should
// treat that as a warning and let the client fall back to the JSON index.
func (p *DocsPlugin) buildSearchAssets(ctx *BuildHookCtx, pages []docs.Page, engine string, maxResults int) error {
	outDir := filepath.Join(ctx.OutDir, searchDir)
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return fmt.Errorf("creating search dir: %w", err)
	}

	searchJS := searchassets.SearchJS
	if maxResults > 0 {
		searchJS = bytes.ReplaceAll(searchJS, []byte("var MAX_RESULTS = 8;"),
			[]byte(fmt.Sprintf("var MAX_RESULTS = %d;", maxResults)))
	}
	if err := os.WriteFile(filepath.Join(outDir, "search.js"), searchJS, 0644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(outDir, "search.css"), searchassets.SearchCSS, 0644); err != nil {
		return err
	}

	if engine != "docfind" {
		return nil
	}

	documents := buildSearchDocuments(pages)
	if len(documents) == 0 {
		return nil
	}

	wasmBytes, err := docfind.Build(context.Background(), documents)
	if err != nil {
		return fmt.Errorf("docfind: %w", err)
	}
	if err := os.WriteFile(filepath.Join(outDir, docfind.WASMName), wasmBytes, 0644); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(outDir, docfind.DocfindJSName), docfind.DocfindJS, 0644)
}

// generateSearchBarTSX returns the source of the SearchBar component that the
// docs plugin generates into .krate/gen/docs/ and renders on every docs page.
func generateSearchBarTSX() string {
	return `// Auto-generated by krate docs plugin
export default function SearchBar() {
  return (
    <>
      <Head>
        <link rel="stylesheet" href="/docs/search/search.css" />
      </Head>
      <button type="button" class="krate-search-trigger" id="krate-search-trigger" aria-label="Search documentation" aria-haspopup="dialog" aria-expanded="false">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="7"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>
        <span class="krate-search-trigger-label">Search</span>
        <kbd class="krate-search-kbd">Ctrl K</kbd>
      </button>
      <div class="krate-search-backdrop" id="krate-search-backdrop"></div>
      <div class="krate-search-dialog" id="krate-search-dialog" role="dialog" aria-modal="true" aria-label="Search documentation" hidden>
        <div class="krate-search-box">
          <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="7"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>
          <input id="krate-search-input" class="krate-search-input" type="search" placeholder="Search documentation..." autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" />
          <kbd class="krate-search-esc">ESC</kbd>
        </div>
        <div class="krate-search-results" id="krate-search-results"></div>
      </div>
      <script src="/docs/search/search.js" />
    </>
  );
}
`
}

// searchBarImportRel computes the relative import path from a generated page
// file's directory to the generated SearchBar component.
func searchBarImportRel(tsxPath, genDir string) string {
	rel, err := filepath.Rel(filepath.Dir(tsxPath), filepath.Join(genDir, "SearchBar"))
	if err != nil {
		return "./SearchBar"
	}
	rel = filepath.ToSlash(rel)
	if !strings.HasPrefix(rel, ".") {
		rel = "./" + rel
	}
	return rel
}
