package plugin

import (
	"fmt"
	"sort"
	"sync"
	"time"

	"krate-compiler/internal/ast"
	"krate-compiler/internal/config"
)

// Plugin is the unified plugin interface. Every plugin — built-in or community —
// implements this single interface. Plugins declare which lifecycle hooks they
// use via Hooks(). Only non-nil hooks are called.
type Plugin interface {
	// Name returns a unique identifier for this plugin.
	Name() string
	// Order returns execution priority. Lower values run first. Default is 50.
	Order() int
	// Hooks returns the lifecycle hooks this plugin implements.
	Hooks() PluginHooks
}

// PluginHooks holds optional lifecycle hook functions.
// Only non-nil hooks are invoked. Plugins implement the hooks they need.
type PluginHooks struct {
	// BeforeBuild runs before any page is built. Plugins can generate TSX files
	// and append them to ctx.GeneratedPages to create new pages.
	BeforeBuild func(ctx *BuildHookCtx) error

	// AfterParse runs after a page's source is parsed into an AST.
	// Useful for inspecting or modifying the AST before rendering.
	AfterParse func(ctx *ParseHookCtx) error

	// AfterMarkdownParse runs after a markdown page is rendered to HTML.
	// Plugins can modify the HTML before it enters the layout pipeline.
	AfterMarkdownParse func(ctx *MarkdownHookCtx) error

	// AfterRender runs after a page is rendered to HTML but BEFORE layout
	// wrapping. Plugins can modify HTML, inject head content, or add CSS.
	AfterRender func(ctx *RenderHookCtx) error

	// GenerateRoutes runs after BeforeBuild. Return virtual pages that should
	// be built alongside real source pages.
	GenerateRoutes func(ctx *BuildHookCtx) ([]Route, error)

	// AfterPage runs after a page is fully built including layout wrapping.
	// Receives the final HTML and OutName. Plugins can modify output.
	AfterPage func(ctx *PageHookCtx) error

	// AfterBuild runs once after ALL pages are built and aggregate work is done.
	// The full set of page results and merged CSS is available.
	AfterBuild func(ctx *BuildResultHookCtx) error
}

// Route represents a virtual page generated by a plugin.
type Route struct {
	Path    string            `json:"path"`
	Content string            `json:"content"`
	Title   string            `json:"title"`
	Layout  string            `json:"layout,omitempty"`
	Data    map[string]string `json:"data,omitempty"`
}

// GeneratedPage describes a TSX page generated by a plugin (e.g., docs plugin).
type GeneratedPage struct {
	Path  string `json:"path"`  // absolute filesystem path to the generated .tsx file
	Route string `json:"route"` // URL path e.g. "docs/getting-started"
}

// ---------------------------------------------------------------------------
// Hook context types
// ---------------------------------------------------------------------------

// BuildHookCtx is passed to BeforeBuild and GenerateRoutes hooks.
type BuildHookCtx struct {
	Root           string          `json:"root"`
	OutDir         string          `json:"outDir"`
	Config         interface{}     `json:"config,omitempty"` // *config.Config
	Pages          []string        `json:"pages"`
	GeneratedPages *[]GeneratedPage `json:"generatedPages,omitempty"` // mutable — append generated pages here
	DevMode        bool            `json:"devMode"`
}

// ParseHookCtx is passed to AfterParse hook after a page's source is parsed.
type ParseHookCtx struct {
	Page    string      `json:"page"`
	Program *ast.Program `json:"program,omitempty"`
}

// MarkdownHookCtx is passed to AfterMarkdownParse hook after markdown rendering.
type MarkdownHookCtx struct {
	Page  string `json:"page"`
	HTML  string `json:"html"` // mutable — plugin can modify rendered HTML
	Title string `json:"title"`
	Route string `json:"route"`
}

// RenderHookCtx is passed to AfterRender hook after a page is fully rendered
// but before layout wrapping. All pointer fields are mutable.
type RenderHookCtx struct {
	Page     string `json:"page"`
	HTML     string `json:"html"` // mutable — plugin can modify rendered HTML
	HeadHTML string `json:"headHTML"` // mutable — plugin can inject head content
	HasJS    bool   `json:"hasJS"`
	RawCSS   string `json:"rawCSS"` // mutable — plugin can inject additional CSS
}

// PageHookCtx is passed to AfterPage hook after a page is fully built
// including layout wrapping. All pointer fields are mutable.
type PageHookCtx struct {
	Page     string `json:"page"`
	OutName  string `json:"outName"`
	HTML     string `json:"html"` // mutable — plugin can modify final HTML
	HeadHTML string `json:"headHTML"` // mutable — plugin can inject head content
	HasJS    bool   `json:"hasJS"`
}

// BuildResultHookCtx is passed to AfterBuild hook after all pages are built.
type BuildResultHookCtx struct {
	Root   string       `json:"root"`
	OutDir string       `json:"outDir"`
	Config interface{}  `json:"config,omitempty"` // *config.Config
	Pages  []PageResult `json:"pages"`
	CSS    string       `json:"css"`
}

// PageResult is a single page's output in the AfterBuild hook.
type PageResult struct {
	Page     string `json:"page"`
	OutName  string `json:"outName"`
	HTML     string `json:"html"`
	HeadHTML string `json:"headHTML"`
	HasJS    bool   `json:"hasJS"`
}

// ---------------------------------------------------------------------------
// Plugin registry
// ---------------------------------------------------------------------------

type pluginEntry struct {
	plugin Plugin
	order  int
}

// Registry holds all registered plugins (single unified registry).
type Registry struct {
	mu      sync.Mutex
	plugins []pluginEntry
}

// NewRegistry creates an empty plugin registry.
func NewRegistry() *Registry {
	return &Registry{}
}

// Add registers a plugin. Returns error on duplicate name.
func (r *Registry) Add(p Plugin) error {
	r.mu.Lock()
	defer r.mu.Unlock()
	name := p.Name()
	for _, e := range r.plugins {
		if e.plugin.Name() == name {
			return fmt.Errorf("plugin %q already registered", name)
		}
	}
	order := p.Order()
	if order == 0 {
		order = 50
	}
	r.plugins = append(r.plugins, pluginEntry{plugin: p, order: order})
	return nil
}

// Sorted returns all plugins sorted by Order (ascending).
func (r *Registry) Sorted() []Plugin {
	r.mu.Lock()
	defer r.mu.Unlock()
	sorted := make([]pluginEntry, len(r.plugins))
	copy(sorted, r.plugins)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].order < sorted[j].order
	})
	result := make([]Plugin, len(sorted))
	for i, e := range sorted {
		result[i] = e.plugin
	}
	return result
}

// List returns all registered plugins.
func (r *Registry) List() []Plugin {
	return r.Sorted()
}

// DefaultRegistry is the global plugin registry.
var DefaultRegistry = NewRegistry()

// Register adds a plugin to the default registry.
func Register(p Plugin) error {
	return DefaultRegistry.Add(p)
}

// ---------------------------------------------------------------------------
// Convenience helpers
// ---------------------------------------------------------------------------

// HookFunc is a convenience type that implements Plugin using plain functions.
type HookFunc struct {
	name  string
	order int
	hooks PluginHooks
}

func (h *HookFunc) Name() string           { return h.name }
func (h *HookFunc) Order() int             { return h.order }
func (h *HookFunc) Hooks() PluginHooks     { return h.hooks }

// NewHookFunc creates a Plugin from a name, order, and hooks.
func NewHookFunc(name string, order int, hooks PluginHooks) Plugin {
	return &HookFunc{name: name, order: order, hooks: hooks}
}

// ---------------------------------------------------------------------------
// Hook runners
// ---------------------------------------------------------------------------

const hookTimeout = 30 * time.Second

func runHook(name, hook string, fn func() error) error {
	done := make(chan error, 1)
	go func() {
		done <- fn()
	}()
	select {
	case err := <-done:
		if err != nil {
			return fmt.Errorf("plugin %q hook %s: %w", name, hook, err)
		}
		return nil
	case <-time.After(hookTimeout):
		return fmt.Errorf("plugin %q hook %s timed out after %v", name, hook, hookTimeout)
	}
}

// RunBeforeBuild runs all BeforeBuild hooks sorted by order.
func RunBeforeBuild(ctx *BuildHookCtx) error {
	for _, p := range DefaultRegistry.Sorted() {
		h := p.Hooks()
		if h.BeforeBuild == nil {
			continue
		}
		if err := runHook(p.Name(), "BeforeBuild", func() error { return h.BeforeBuild(ctx) }); err != nil {
			return err
		}
	}
	return nil
}

// RunAfterParse runs all AfterParse hooks sorted by order.
func RunAfterParse(ctx *ParseHookCtx) error {
	for _, p := range DefaultRegistry.Sorted() {
		h := p.Hooks()
		if h.AfterParse == nil {
			continue
		}
		if err := runHook(p.Name(), "AfterParse", func() error { return h.AfterParse(ctx) }); err != nil {
			return err
		}
	}
	return nil
}

// RunAfterMarkdownParse runs all AfterMarkdownParse hooks sorted by order.
func RunAfterMarkdownParse(ctx *MarkdownHookCtx) error {
	for _, p := range DefaultRegistry.Sorted() {
		h := p.Hooks()
		if h.AfterMarkdownParse == nil {
			continue
		}
		if err := runHook(p.Name(), "AfterMarkdownParse", func() error { return h.AfterMarkdownParse(ctx) }); err != nil {
			return err
		}
	}
	return nil
}

// RunAfterRender runs all AfterRender hooks sorted by order.
func RunAfterRender(ctx *RenderHookCtx) error {
	for _, p := range DefaultRegistry.Sorted() {
		h := p.Hooks()
		if h.AfterRender == nil {
			continue
		}
		if err := runHook(p.Name(), "AfterRender", func() error { return h.AfterRender(ctx) }); err != nil {
			return err
		}
	}
	return nil
}

// RunGenerateRoutes runs all GenerateRoutes hooks and returns combined routes.
func RunGenerateRoutes(ctx *BuildHookCtx) ([]Route, error) {
	var allRoutes []Route
	for _, p := range DefaultRegistry.Sorted() {
		h := p.Hooks()
		if h.GenerateRoutes == nil {
			continue
		}
		var routes []Route
		if err := runHook(p.Name(), "GenerateRoutes", func() error {
			var err error
			routes, err = h.GenerateRoutes(ctx)
			return err
		}); err != nil {
			return nil, err
		}
		allRoutes = append(allRoutes, routes...)
	}
	return allRoutes, nil
}

// RunAfterPage runs all AfterPage hooks sorted by order.
func RunAfterPage(ctx *PageHookCtx) error {
	for _, p := range DefaultRegistry.Sorted() {
		h := p.Hooks()
		if h.AfterPage == nil {
			continue
		}
		if err := runHook(p.Name(), "AfterPage", func() error { return h.AfterPage(ctx) }); err != nil {
			return err
		}
	}
	return nil
}

// RunAfterBuild runs all AfterBuild hooks sorted by order.
func RunAfterBuild(ctx *BuildResultHookCtx) error {
	for _, p := range DefaultRegistry.Sorted() {
		h := p.Hooks()
		if h.AfterBuild == nil {
			continue
		}
		if err := runHook(p.Name(), "AfterBuild", func() error { return h.AfterBuild(ctx) }); err != nil {
			return err
		}
	}
	return nil
}

// ---------------------------------------------------------------------------
// Community plugin helpers
// ---------------------------------------------------------------------------

// RunCommunityPlugins runs all configured community plugins for the given hook.
// pluginConfig is the full plugins list from config; hookName identifies which
// hook is being executed; hookCtx is the JSON-serializable context for the hook.
// Community plugins are JavaScript modules (config plugins[].module points to a
// .js/.mjs/.cjs file) executed inside the embedded QuickJS runtime.
func RunCommunityPlugins(hookName string, plugins []config.PluginConfig, root, outDir string, hookCtx interface{}) error {
	for _, pc := range plugins {
		if pc.Module == "" {
			continue
		}
		if err := runCommunityHook(hookName, pc, root, outDir, hookCtx); err != nil {
			return fmt.Errorf("community plugin %q: %w", pc.Name, err)
		}
	}
	return nil
}
