package plugin

import (
	"fmt"
	"os"
	"sort"
	"sync"
	"sync/atomic"
	"time"

	"github.com/kratejs/krate/packages/compiler/ast"
	"github.com/kratejs/krate/packages/compiler/internal/config"
	"github.com/kratejs/krate/packages/compiler/internal/content"
)

// verbose enables per-hook trace output to stderr. It is a process-global
// because community hooks run on concurrent per-page goroutines; SetVerbose is
// called once at startup before any build begins.
var verbose atomic.Bool

// SetVerbose toggles per-hook trace output (`--verbose`).
func SetVerbose(v bool) { verbose.Store(v) }

// hookTraceColor is a dim grey used for the verbose hook trace lines.
const hookTraceColor = "\033[90m"

// traceHook prints a one-line trace of a hook invocation (plugin name, hook,
// duration, outcome) when verbose mode is on. It never changes the error.
func traceHook(name, hook string, elapsed time.Duration, err error) {
	if !verbose.Load() {
		return
	}
	label := name
	if label == "" {
		label = "unnamed"
	}
	if err != nil {
		fmt.Fprintf(os.Stderr, "  %s[plugin:%s]%s %s %s(%.1fms, error)%s\n",
			hookTraceColor, label, cReset, hook, hookTraceColor, float64(elapsed.Microseconds())/1000, cReset)
		return
	}
	fmt.Fprintf(os.Stderr, "  %s[plugin:%s]%s %s %s(%.1fms)%s\n",
		hookTraceColor, label, cReset, hook, hookTraceColor, float64(elapsed.Microseconds())/1000, cReset)
}

// cReset terminates ANSI styling in this package. It mirrors the build
// package's reset sequence so trace lines and build output nest cleanly.
const cReset = "\033[0m"

// Plugin is the unified plugin interface. Every plugin — built-in or community —
// implements this single interface. Plugins declare which lifecycle hooks they
// use via Hooks(). Only non-nil hooks are called.
type Plugin interface {
	// Name returns a unique identifier for this plugin.
	Name() string
	// Order returns execution priority. Lower values run first. Default is 50.
	Order() int
	// Hooks returns the lifecycle hooks this plugin implements.
	Hooks() PluginHooks
}

// PluginHooks holds optional lifecycle hook functions.
// Only non-nil hooks are invoked. Plugins implement the hooks they need.
type PluginHooks struct {
	// BeforeBuild runs before any page is built. Plugins can generate TSX files
	// and append them to ctx.GeneratedPages to create new pages.
	BeforeBuild func(ctx *BuildHookCtx) error

	// AfterParse runs after a page's source is parsed into an AST.
	// Useful for inspecting or modifying the AST before rendering.
	AfterParse func(ctx *ParseHookCtx) error

	// AfterMarkdownParse runs after a markdown page is rendered to HTML.
	// Plugins can modify the HTML before it enters the layout pipeline.
	AfterMarkdownParse func(ctx *MarkdownHookCtx) error

	// AfterRender runs after a page is rendered to HTML but BEFORE layout
	// wrapping. Plugins can modify HTML, inject head content, or add CSS.
	AfterRender func(ctx *RenderHookCtx) error

	// GenerateRoutes runs after BeforeBuild. Return virtual pages that should
	// be built alongside real source pages.
	GenerateRoutes func(ctx *BuildHookCtx) ([]Route, error)

	// AfterPage runs after a page is fully built including layout wrapping.
	// Receives the final HTML and OutName. Plugins can modify output.
	AfterPage func(ctx *PageHookCtx) error

	// AfterBuild runs once after ALL pages are built and aggregate work is done.
	// The full set of page results and merged CSS is available.
	AfterBuild func(ctx *BuildResultHookCtx) error

	// Collections returns content collections this plugin contributes to the
	// site. Contributed collections are merged into the effective content
	// config alongside any `content:` declarations in krate.config.ts and are
	// validated, typed, and exposed to the MCP content tools like configured
	// collections. The plugin remains responsible for rendering its own pages.
	Collections func(cfg *config.Config) []CollectionContribution
}

// CollectionContribution is a content collection a plugin contributes. The
// Name is the collection name (e.g. "docs"); Dir is the collection directory
// relative to the project root; Schema optionally carries a validation schema
// for tooling that surfaces collections (MCP, build validation).
type CollectionContribution struct {
	Name   string
	Dir    string
	Schema map[string]content.Field
}

// Route represents a virtual page generated by a plugin.
type Route struct {
	Path    string            `json:"path"`
	Content string            `json:"content"`
	Title   string            `json:"title"`
	Layout  string            `json:"layout,omitempty"`
	Data    map[string]string `json:"data,omitempty"`
}

// GeneratedPage describes a TSX page generated by a plugin (e.g., docs plugin).
type GeneratedPage struct {
	Path  string `json:"path"`  // absolute filesystem path to the generated .tsx file
	Route string `json:"route"` // URL path e.g. "docs/getting-started"
}

// ---------------------------------------------------------------------------
// Hook context types
// ---------------------------------------------------------------------------

// BuildHookCtx is passed to BeforeBuild and GenerateRoutes hooks.
type BuildHookCtx struct {
	Root           string           `json:"root"`
	OutDir         string           `json:"outDir"`
	Config         interface{}      `json:"config,omitempty"` // *config.Config
	Pages          []string         `json:"pages"`
	GeneratedPages *[]GeneratedPage `json:"generatedPages,omitempty"` // mutable — append generated pages here
	DevMode        bool             `json:"devMode"`
}

// ParseHookCtx is passed to AfterParse hook after a page's source is parsed.
type ParseHookCtx struct {
	Page    string       `json:"page"`
	Program *ast.Program `json:"program,omitempty"`
}

// MarkdownHookCtx is passed to AfterMarkdownParse hook after markdown rendering.
type MarkdownHookCtx struct {
	Page  string `json:"page"`
	HTML  string `json:"html"` // mutable — plugin can modify rendered HTML
	Title string `json:"title"`
	Route string `json:"route"`
}

// RenderHookCtx is passed to AfterRender hook after a page is fully rendered
// but before layout wrapping. All pointer fields are mutable.
type RenderHookCtx struct {
	Page     string `json:"page"`
	HTML     string `json:"html"`     // mutable — plugin can modify rendered HTML
	HeadHTML string `json:"headHTML"` // mutable — plugin can inject head content
	HasJS    bool   `json:"hasJS"`
	RawCSS   string `json:"rawCSS"` // mutable — plugin can inject additional CSS
}

// PageHookCtx is passed to AfterPage hook after a page is fully built
// including layout wrapping. All pointer fields are mutable.
type PageHookCtx struct {
	Page     string `json:"page"`
	OutName  string `json:"outName"`
	HTML     string `json:"html"`     // mutable — plugin can modify final HTML
	HeadHTML string `json:"headHTML"` // mutable — plugin can inject head content
	HasJS    bool   `json:"hasJS"`
}

// BuildResultHookCtx is passed to AfterBuild hook after all pages are built.
type BuildResultHookCtx struct {
	Root    string       `json:"root"`
	OutDir  string       `json:"outDir"`
	Config  interface{}  `json:"config,omitempty"` // *config.Config
	Pages   []PageResult `json:"pages"`
	CSS     string       `json:"css"`
	DevMode bool         `json:"devMode"`
}

// PageResult is a single page's output in the AfterBuild hook.
type PageResult struct {
	Page     string `json:"page"`
	OutName  string `json:"outName"`
	HTML     string `json:"html"`
	HeadHTML string `json:"headHTML"`
	HasJS    bool   `json:"hasJS"`
}

// ---------------------------------------------------------------------------
// Plugin registry
// ---------------------------------------------------------------------------

type pluginEntry struct {
	plugin Plugin
	order  int
}

// Registry holds all registered plugins (single unified registry).
type Registry struct {
	mu      sync.Mutex
	plugins []pluginEntry
}

// NewRegistry creates an empty plugin registry.
func NewRegistry() *Registry {
	return &Registry{}
}

// Add registers a plugin. Returns error on duplicate name.
func (r *Registry) Add(p Plugin) error {
	r.mu.Lock()
	defer r.mu.Unlock()
	name := p.Name()
	for _, e := range r.plugins {
		if e.plugin.Name() == name {
			return fmt.Errorf("plugin %q already registered", name)
		}
	}
	order := p.Order()
	if order == 0 {
		order = 50
	}
	r.plugins = append(r.plugins, pluginEntry{plugin: p, order: order})
	return nil
}

// Sorted returns all plugins sorted by Order (ascending).
func (r *Registry) Sorted() []Plugin {
	r.mu.Lock()
	defer r.mu.Unlock()
	sorted := make([]pluginEntry, len(r.plugins))
	copy(sorted, r.plugins)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].order < sorted[j].order
	})
	result := make([]Plugin, len(sorted))
	for i, e := range sorted {
		result[i] = e.plugin
	}
	return result
}

// List returns all registered plugins.
func (r *Registry) List() []Plugin {
	return r.Sorted()
}

// DefaultRegistry is the global plugin registry.
var DefaultRegistry = NewRegistry()

// Register adds a plugin to the default registry.
func Register(p Plugin) error {
	return DefaultRegistry.Add(p)
}

// ---------------------------------------------------------------------------
// Convenience helpers
// ---------------------------------------------------------------------------

// HookFunc is a convenience type that implements Plugin using plain functions.
type HookFunc struct {
	name  string
	order int
	hooks PluginHooks
}

func (h *HookFunc) Name() string       { return h.name }
func (h *HookFunc) Order() int         { return h.order }
func (h *HookFunc) Hooks() PluginHooks { return h.hooks }

// NewHookFunc creates a Plugin from a name, order, and hooks.
func NewHookFunc(name string, order int, hooks PluginHooks) Plugin {
	return &HookFunc{name: name, order: order, hooks: hooks}
}

// ---------------------------------------------------------------------------
// Hook runners
// ---------------------------------------------------------------------------

const hookTimeout = 30 * time.Second

// afterBuildHookTimeout bounds the AfterBuild hook. It is larger than the
// per-page hook budget because AfterBuild runs site-wide post-processing (e.g.
// the Pagefind indexer over the whole output tree), which can legitimately take
// minutes on large sites.
const afterBuildHookTimeout = 5 * time.Minute

func runHook(name, hook string, fn func() error) error {
	return runHookTimeout(name, hook, hookTimeout, fn)
}

func runHookTimeout(name, hook string, timeout time.Duration, fn func() error) error {
	start := time.Now()
	done := make(chan error, 1)
	go func() {
		done <- fn()
	}()

	var err error
	select {
	case err = <-done:
		if err != nil {
			err = fmt.Errorf("plugin %q hook %s: %w", name, hook, err)
		}
	case <-time.After(timeout):
		err = fmt.Errorf("plugin %q hook %s timed out after %v", name, hook, timeout)
	}
	traceHook(name, hook, time.Since(start), err)
	return err
}

// RunBeforeBuild runs all BeforeBuild hooks sorted by order.
func RunBeforeBuild(ctx *BuildHookCtx) error {
	for _, p := range DefaultRegistry.Sorted() {
		h := p.Hooks()
		if h.BeforeBuild == nil {
			continue
		}
		if err := runHook(p.Name(), "BeforeBuild", func() error { return h.BeforeBuild(ctx) }); err != nil {
			return err
		}
	}
	return nil
}

// RunAfterParse runs all AfterParse hooks sorted by order.
func RunAfterParse(ctx *ParseHookCtx) error {
	for _, p := range DefaultRegistry.Sorted() {
		h := p.Hooks()
		if h.AfterParse == nil {
			continue
		}
		if err := runHook(p.Name(), "AfterParse", func() error { return h.AfterParse(ctx) }); err != nil {
			return err
		}
	}
	return nil
}

// RunAfterMarkdownParse runs all AfterMarkdownParse hooks sorted by order.
func RunAfterMarkdownParse(ctx *MarkdownHookCtx) error {
	for _, p := range DefaultRegistry.Sorted() {
		h := p.Hooks()
		if h.AfterMarkdownParse == nil {
			continue
		}
		if err := runHook(p.Name(), "AfterMarkdownParse", func() error { return h.AfterMarkdownParse(ctx) }); err != nil {
			return err
		}
	}
	return nil
}

// RunAfterRender runs all AfterRender hooks sorted by order.
func RunAfterRender(ctx *RenderHookCtx) error {
	for _, p := range DefaultRegistry.Sorted() {
		h := p.Hooks()
		if h.AfterRender == nil {
			continue
		}
		if err := runHook(p.Name(), "AfterRender", func() error { return h.AfterRender(ctx) }); err != nil {
			return err
		}
	}
	return nil
}

// RunGenerateRoutes runs all GenerateRoutes hooks and returns combined routes.
func RunGenerateRoutes(ctx *BuildHookCtx) ([]Route, error) {
	var allRoutes []Route
	for _, p := range DefaultRegistry.Sorted() {
		h := p.Hooks()
		if h.GenerateRoutes == nil {
			continue
		}
		var routes []Route
		if err := runHook(p.Name(), "GenerateRoutes", func() error {
			var err error
			routes, err = h.GenerateRoutes(ctx)
			return err
		}); err != nil {
			return nil, err
		}
		allRoutes = append(allRoutes, routes...)
	}
	return allRoutes, nil
}

// RunAfterPage runs all AfterPage hooks sorted by order.
func RunAfterPage(ctx *PageHookCtx) error {
	for _, p := range DefaultRegistry.Sorted() {
		h := p.Hooks()
		if h.AfterPage == nil {
			continue
		}
		if err := runHook(p.Name(), "AfterPage", func() error { return h.AfterPage(ctx) }); err != nil {
			return err
		}
	}
	return nil
}

// RunAfterBuild runs all AfterBuild hooks sorted by order.
func RunAfterBuild(ctx *BuildResultHookCtx) error {
	for _, p := range DefaultRegistry.Sorted() {
		h := p.Hooks()
		if h.AfterBuild == nil {
			continue
		}
		if err := runHookTimeout(p.Name(), "AfterBuild", afterBuildHookTimeout, func() error { return h.AfterBuild(ctx) }); err != nil {
			return err
		}
	}
	return nil
}

// ContributedCollections returns every collection contributed by registered
// plugins, keyed by collection name. Later declarations (higher plugin order)
// override earlier ones per name.
func ContributedCollections(reg *Registry, cfg *config.Config) map[string]content.Collection {
	out := map[string]content.Collection{}
	for _, p := range reg.Sorted() {
		h := p.Hooks()
		if h.Collections == nil {
			continue
		}
		for _, c := range h.Collections(cfg) {
			out[c.Name] = content.Collection{Dir: c.Dir, Schema: c.Schema}
		}
	}
	return out
}

// DefaultContributedCollections returns plugin-contributed collections from the
// default registry.
func DefaultContributedCollections(cfg *config.Config) map[string]content.Collection {
	return ContributedCollections(DefaultRegistry, cfg)
}

// ---------------------------------------------------------------------------
// Community plugin helpers
// ---------------------------------------------------------------------------

// HasPerPageHooks reports whether any registered native plugin implements a
// hook that runs per page (AfterParse/AfterMarkdownParse/AfterRender/AfterPage).
// When true, page output may depend on plugin side effects the disk build cache
// cannot replay, so callers disable page-level caching.
func HasPerPageHooks() bool {
	for _, p := range DefaultRegistry.Sorted() {
		h := p.Hooks()
		if h.AfterParse != nil || h.AfterMarkdownParse != nil || h.AfterRender != nil || h.AfterPage != nil {
			return true
		}
	}
	return false
}

// RunCommunityPlugins runs all configured community plugins for the given hook.
// pluginConfig is the full plugins list from config; hookName identifies which
// hook is being executed; hookCtx is the JSON-serializable context for the hook.
// Community plugins are JavaScript/TypeScript modules (config plugins[].module
// points to a .js/.mjs/.cjs/.ts/.tsx file) executed inside the embedded QuickJS
// runtime; esbuild transpiles TS entries before evaluation.
//
// The optional env carries build-wide context (pages dir, dev flag, resolved
// config) that the richer `krate` object exposes. When omitted it is derived
// from hookCtx where possible.
func RunCommunityPlugins(hookName string, plugins []config.PluginConfig, root, outDir string, hookCtx interface{}, env ...CommunityEnv) error {
	e := resolveCommunityEnv(hookCtx, env)
	for _, pc := range plugins {
		if pc.Module == "" {
			continue
		}
		if err := runCommunityHook(hookName, pc, root, outDir, e, hookCtx); err != nil {
			return fmt.Errorf("community plugin %q: %w", pc.Name, err)
		}
	}
	return nil
}

// CommunityEnv is build-wide context shared across every community plugin hook
// invocation. It feeds the richer `krate` object (JS) and Go hook contexts.
type CommunityEnv struct {
	PagesDir string
	DevMode  bool
	Config   *config.Config
}

// resolveCommunityEnv uses the caller-supplied env when present, otherwise
// derives what it can from the hook context.
func resolveCommunityEnv(hookCtx interface{}, env []CommunityEnv) CommunityEnv {
	if len(env) > 0 {
		return env[0]
	}
	var e CommunityEnv
	switch c := hookCtx.(type) {
	case *BuildHookCtx:
		e.DevMode = c.DevMode
		if cfg, ok := c.Config.(*config.Config); ok {
			e.Config = cfg
		}
	case *BuildResultHookCtx:
		e.DevMode = c.DevMode
		if cfg, ok := c.Config.(*config.Config); ok {
			e.Config = cfg
		}
	}
	return e
}
