// Package routetypes generates TypeScript declaration files describing a
// project's route surface. The generated `.d.ts` gives `<Link href>`, route
// params, and navigation code end-to-end type safety without any runtime cost.
// It is a pure string generator (no filesystem access) so it is trivially
// testable and reusable by the build pipeline, the MCP server, and tooling.
package routetypes

import (
	"sort"
	"strings"
)

// Route is a single page route known at build time.
type Route struct {
	// Pattern is the URL path with dynamic segments in bracket form, e.g.
	// "/video/[id]" or "/user/[username]/posts/[postId]". Static routes have no
	// brackets.
	Pattern string
	// Source is the page's source path relative to the project root, for
	// documentation and IDE hover.
	Source string
	// Mode is the rendered mode label ("ssg", "isr", "ssr", "streaming") when
	// known; informational only.
	Mode string
}

// Param returns the parameter names embedded in a route pattern, in order.
// e.g. "/user/[username]/posts/[postId]" -> ["username", "postId"];
// catch-all segments "[...slug]" yield "slug".
func (r Route) Param() []string {
	return Params(r.Pattern)
}

// Params extracts parameter names from a route pattern.
func Params(pattern string) []string {
	var out []string
	for _, seg := range strings.Split(strings.Trim(pattern, "/"), "/") {
		if name, ok := segmentParam(seg); ok {
			out = append(out, name)
		}
	}
	return out
}

// segmentParam returns the parameter name for a dynamic segment.
func segmentParam(seg string) (string, bool) {
	if len(seg) < 3 || seg[0] != '[' || seg[len(seg)-1] != ']' {
		return "", false
	}
	name := seg[1 : len(seg)-1]
	name = strings.TrimPrefix(name, "...")
	if name == "" {
		return "", false
	}
	return name, true
}

// Normalize collapses a route pattern to canonical "/"-prefixed, trailing-slash
// free form so "/about/" and "about" compare equal. The build's root sentinel
// "." (and "index") normalize to "/".
func Normalize(p string) string {
	if p == "" || p == "." || p == "index" {
		return "/"
	}
	if !strings.HasPrefix(p, "/") {
		p = "/" + p
	}
	if len(p) > 1 {
		p = strings.TrimRight(p, "/")
		if p == "" {
			p = "/"
		}
	}
	return p
}

// Dedupe returns the routes with normalized, unique patterns, sorted
// deterministically.
func Dedupe(routes []Route) []Route {
	seen := make(map[string]bool)
	var out []Route
	for _, r := range routes {
		if strings.TrimSpace(r.Pattern) == "" {
			continue
		}
		p := Normalize(r.Pattern)
		if seen[p] {
			continue
		}
		seen[p] = true
		r.Pattern = p
		out = append(out, r)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Pattern < out[j].Pattern })
	return out
}

// Generate renders the route declarations as a TypeScript module body. The
// output exports `StaticRoute`, `DynamicRoute`, `Route`, `RouteParams`, and
// `routes`. It does NOT augment any globals - see Bridge for that.
func Generate(routes []Route) string {
	uniq := Dedupe(routes)

	var static, dynamic, paramEntries, manifestEntries []string
	for _, r := range uniq {
		params := r.Param()
		manifestEntries = append(manifestEntries, manifestEntry(r, params))
		if len(params) == 0 {
			static = append(static, tsString(r.Pattern))
			continue
		}
		dynamic = append(dynamic, templateLiteral(r.Pattern))
		paramEntries = append(paramEntries, paramEntry(r.Pattern, params))
	}

	var b strings.Builder
	b.WriteString("// AUTO-GENERATED by Krate — do not edit.\n")
	b.WriteString("// Regenerate with `krate build` (or `krate types`).\n\n")
	b.WriteString("export type StaticRoute =\n")
	if len(static) == 0 {
		b.WriteString("  never;\n")
	} else {
		for _, s := range static {
			b.WriteString("  | " + s + "\n")
		}
		b.WriteString("  ;\n")
	}
	b.WriteString("\nexport type DynamicRoute =\n")
	if len(dynamic) == 0 {
		b.WriteString("  never;\n")
	} else {
		for _, d := range dynamic {
			b.WriteString("  | " + d + "\n")
		}
		b.WriteString("  ;\n")
	}
	b.WriteString("\nexport type Route = StaticRoute | DynamicRoute;\n\n")

	b.WriteString("export interface RouteParams {\n")
	if len(paramEntries) == 0 {
		b.WriteString("  // no dynamic routes\n")
	} else {
		for _, e := range paramEntries {
			b.WriteString("  " + e + "\n")
		}
	}
	b.WriteString("}\n\n")

	b.WriteString("export interface RouteManifestEntry {\n")
	b.WriteString("  readonly route: Route;\n")
	b.WriteString("  readonly source: string;\n")
	b.WriteString("  readonly params: readonly string[];\n")
	b.WriteString("  readonly mode?: string;\n")
	b.WriteString("}\n\n")
	b.WriteString("export const routes = [\n")
	for _, e := range manifestEntries {
		b.WriteString("  " + e + ",\n")
	}
	b.WriteString("] as const satisfies readonly RouteManifestEntry[];\n")

	return b.String()
}

// Bridge renders a project-level `krate-env.d.ts` that imports the generated
// route/content declarations and augments the runtime's global `Krate`
// extension point, which `@krate/runtime`'s `<Link href>` / params typing
// consult. `routesPath` and `contentPath` are module specifiers relative to the
// bridge file (e.g. "./.krate/types/routes.js").
func Bridge(routesPath, contentPath string) string {
	var b strings.Builder
	b.WriteString("// AUTO-GENERATED by Krate — do not edit.\n")
	b.WriteString("// Provides typed routes/content to @krate/runtime. Include this file in\n")
	b.WriteString("// your tsconfig (the default `include: [\"src\"]` picks it up when placed\n")
	b.WriteString("// beside your source).\n\n")
	b.WriteString("import type { Route, RouteParams } from " + tsString(routesPath) + ";\n")
	if contentPath != "" {
		b.WriteString("import type { ContentTypes } from " + tsString(contentPath) + ";\n")
	}
	b.WriteString("\ndeclare global {\n")
	b.WriteString("  namespace Krate {\n")
	b.WriteString("    interface TypedRoutes {\n")
	b.WriteString("      href: Route;\n")
	b.WriteString("      params: RouteParams;\n")
	if contentPath != "" {
		b.WriteString("      content: ContentTypes;\n")
	}
	b.WriteString("    }\n")
	b.WriteString("  }\n")
	b.WriteString("}\n\n")
	b.WriteString("export {};\n")
	return b.String()
}

// templateLiteral renders a route pattern as a TypeScript template literal
// type. Static segments are literal; dynamic segments are `${string}` (a
// catch-all also maps to `${string}` for typing purposes).
func templateLiteral(pattern string) string {
	segs := strings.Split(strings.Trim(pattern, "/"), "/")
	var parts []string
	for _, seg := range segs {
		if _, ok := segmentParam(seg); !ok {
			parts = append(parts, seg)
			continue
		}
		parts = append(parts, "${string}")
	}
	return "`/" + strings.Join(parts, "/") + "`"
}

func manifestEntry(r Route, params []string) string {
	fields := []string{"route: " + tsString(r.Pattern), "source: " + tsString(r.Source)}
	var quoted []string
	for _, p := range params {
		quoted = append(quoted, tsString(p))
	}
	fields = append(fields, "params: ["+strings.Join(quoted, ", ")+"]")
	if r.Mode != "" {
		fields = append(fields, "mode: "+tsString(r.Mode))
	}
	return "{ " + strings.Join(fields, ", ") + " }"
}

func paramEntry(pattern string, params []string) string {
	var fields []string
	for _, p := range params {
		fields = append(fields, p+": string")
	}
	return tsString(pattern) + ": { " + strings.Join(fields, "; ") + " };"
}

func tsString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}
