// krate-plugin-demo - a community plugin written in TypeScript.
// Community plugins run inside krate's embedded QuickJS runtime - no
// subprocess, no stdin/stdout protocol. The plugin module is bundled with
// esbuild (which handles .ts) and evaluated in a fresh VM per hook.
// A community plugin exports:
// - `hooks` - the lifecycle hooks (BeforeBuild, AfterParse, AfterRender, ...)
//   - a `default` factory that returns a serializable descriptor used in the
//     config, e.g. `demoPlugin({ greeting: '...' })`:
//       import demoPlugin from './plugins/krate-plugin-demo';
//       export default { plugins: [demoPlugin({ greeting: 'Hi' })] };
// The factory result `{ name, module, options }` is what lands in the config.
// `module` points back at this file so the compiler can bundle it for QuickJS.
// Each hook receives (ctx, options, krate) where ctx is the JSON-serialized
// hook context, options is the per-plugin options object, and krate is the
// richer build context ({ root, outDir, pagesDir, config, dev, pages, version })
// with capability methods (resolveFile, readFile, emitFile, writeFileToRoot,
// injectHead, injectCSS). Hooks return a result object:
//   { files, routes, generatedPages, html, headHTML, rawCSS, scripts, metaTags }
// (all fields optional; hooks may also return a Promise).
// This demo dogfoods the capabilities: krate.emitFile for output files,
// krate.injectHead / krate.injectCSS for head/CSS injection, typed hooks via
// definePluginHooks<DemoPluginOptions>, and krate.log / krate.warn for output.

import { ASTTypes, definePlugin, definePluginHooks, isAstKind } from "@krate/plugin";
import type { AstNode, Krate, PluginOutput } from "@krate/plugin";

// Typed plugin options: `demoPlugin({ greeting: "..." })` now typechecks, and
// `definePluginHooks<DemoPluginOptions>` types every hook's `options` argument.
interface DemoPluginOptions {
  greeting?: string;
}

const DEMO_CSS =
  ".demo-banner{background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:white;padding:8px 16px;text-align:center;font-size:13px;font-weight:500;}";

function greeting(options: DemoPluginOptions | undefined): string {
  return (options && options.greeting) || "Hello from the Krate Demo Plugin!";
}

export const hooks = definePluginHooks<DemoPluginOptions>({
  // Write a notice file into the output directory via krate.emitFile.
  BeforeBuild(ctx, options, krate: Krate): PluginOutput {
    krate.log("BeforeBuild: greeting =", greeting(options));
    const notice =
      "This file was generated by the krate-plugin-demo.\n" +
      "Hook: BeforeBuild\n" +
      "Greeting: " + greeting(options) + "\n" +
      "Root: " + krate.root + "\n" +
      "Pages dir: " + krate.pagesDir + "\n" +
      "Pages: " + krate.pages.length + "\n" +
      "Version: " + krate.version + "\n";
    krate.emitFile("demo-notice.txt", notice);
    return {};
  },

  // Walk the parsed AST with the typed kind discriminators. This demo counts
  // JSX elements; the same walk could mutate nodes and return { ast }.
  AfterParse(ctx, options, krate: Krate): PluginOutput {
    let jsxCount = 0;
    const walk = (node: unknown): void => {
      if (Array.isArray(node)) {
        for (const child of node) walk(child);
        return;
      }
      if (!node || typeof node !== "object") return;
      if (isAstKind(node, ASTTypes.JSXElement)) jsxCount++;
      for (const value of Object.values(node as AstNode)) walk(value);
    };
    walk(ctx.program);
    krate.log("AfterParse:", ctx.page, "->", jsxCount, "JSX element(s)");
    return {};
  },

  // Prepend a notice banner to markdown pages.
  AfterMarkdownParse(ctx): PluginOutput {
    return {
      html:
        '<div style="background:#e8f4fd;border-left:4px solid #2196f3;padding:12px 16px;margin-bottom:16px;border-radius:4px;font-size:14px;color:#0d47a1;">📝 This page was processed by the <strong>krate-plugin-demo</strong> (AfterMarkdownParse hook)</div>' +
        ctx.html,
    };
  },

  // Inject a banner, meta tag, and CSS into every rendered page. Head/CSS go
  // through the krate capability helpers instead of raw output fields.
  AfterRender(ctx, options, krate: Krate): PluginOutput {
    krate.injectHead('<meta name="generator" content="krate-plugin-demo">');
    krate.injectCSS(DEMO_CSS);
    return {
      html: '<div class="demo-banner">' + greeting(options) + "</div>" + ctx.html,
    };
  },

  // Generate a virtual page.
  GenerateRoutes(): PluginOutput {
    return {
      routes: [
        {
          path: "demo/hello",
          title: "Demo Plugin - Hello",
          content:
            '<div style="padding:40px;text-align:center;"><h1>Hello from Demo Plugin!</h1><p>This page was generated by the community plugin via GenerateRoutes hook.</p><p><a href="/">← Back to home</a></p></div>',
        },
      ],
    };
  },

  // Log each completed page.
  AfterPage(): PluginOutput {
    return {};
  },

  // Write a stats JSON file summarizing the build.
  AfterBuild(ctx, options, krate: Krate): PluginOutput {
    const pages = (ctx.pages || []).map((p) => ({
      page: p.page,
      outName: p.outName,
      hasJS: p.hasJS,
    }));
    const stats = {
      plugin: "krate-plugin-demo",
      version: krate.version,
      totalPages: pages.length,
      hasCSS: Boolean(ctx.css),
      pages,
    };
    krate.emitFile("demo-stats.json", JSON.stringify(stats, null, 2));
    if (pages.length === 0) {
      krate.warn("AfterBuild: no pages were built");
    } else {
      krate.log("AfterBuild: built", pages.length, "pages");
    }
    return {};
  },
});

// Factory used from krate.config.ts: `demoPlugin({ greeting: '...' })`.
export default function demoPlugin(options: DemoPluginOptions = {}) {
  return definePlugin({
    name: "demo",
    order: 10,
    // Point back at this file so the compiler can bundle it. In the Node/tsx
    // config bootstrap this is the real file:// URL; inside the esbuild IIFE
    // (QuickJS) it's empty, which is fine - the compiler already resolved it.
    module: typeof import.meta !== "undefined" && import.meta.url ? import.meta.url : "",
    options,
  });
}
