// krate-plugin-demo — a community plugin written in JavaScript.
//
// Community plugins are plain JS modules that run inside krate's embedded
// QuickJS runtime — no subprocess, no stdin/stdout protocol.
//
// A community plugin exports:
//   - `hooks` — the lifecycle hooks (BeforeBuild, AfterParse, AfterRender, ...)
//   - a `default` factory that returns a serializable descriptor used in the
//     config, e.g. `demoPlugin({ greeting: '...' })`:
//
//       import demoPlugin from './plugins/krate-plugin-demo';
//       export default { plugins: [demoPlugin({ greeting: 'Hi' })] };
//
// The factory result `{ name, module, options }` is what lands in the config.
// `module` points back at this file so the compiler can bundle it for QuickJS.
//
// Each hook receives (ctx, options, krate) where ctx is the JSON-serialized
// hook context, options is the per-plugin options object, and krate is
// { root, outDir, version }. Hooks return a result object:
//
//   { files, routes, generatedPages, html, headHTML, rawCSS }
//
// (all fields optional; hooks may also return a Promise).

const DEMO_CSS =
  ".demo-banner{background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:white;padding:8px 16px;text-align:center;font-size:13px;font-weight:500;}";

export const hooks = {
  // Write a notice file into the output directory.
  BeforeBuild(ctx, options, krate) {
    const greeting = (options && options.greeting) || "Hello from the Krate Demo Plugin!";
    const files = [
      {
        path: "demo-notice.txt",
        content:
          "This file was generated by the krate-plugin-demo.\n" +
          "Hook: BeforeBuild\n" +
          "Greeting: " + greeting + "\n" +
          "Root: " + krate.root + "\n",
      },
    ];
    return { files };
  },

  // Log each page that gets parsed (console.error surfaces as a warning).
  AfterParse(ctx, options, krate) {
    // console.log("[demo] AfterParse: " + ctx.page);
    return {};
  },

  // Prepend a notice banner to markdown pages.
  AfterMarkdownParse(ctx, options, krate) {
    return {
      html:
        '<div style="background:#e8f4fd;border-left:4px solid #2196f3;padding:12px 16px;margin-bottom:16px;border-radius:4px;font-size:14px;color:#0d47a1;">📝 This page was processed by the <strong>krate-plugin-demo</strong> (AfterMarkdownParse hook)</div>' +
        ctx.html,
    };
  },

  // Inject a banner, meta tag, and CSS into every rendered page.
  AfterRender(ctx, options, krate) {
    const greeting = (options && options.greeting) || "Hello from the Krate Demo Plugin!";
    return {
      html: '<div class="demo-banner">' + greeting + "</div>" + ctx.html,
      headHTML: '<meta name="generator" content="krate-plugin-demo">',
      rawCSS: DEMO_CSS,
    };
  },

  // Generate a virtual page.
  GenerateRoutes(ctx, options, krate) {
    return {
      routes: [
        {
          path: "demo/hello",
          title: "Demo Plugin — Hello",
          content:
            '<div style="padding:40px;text-align:center;"><h1>Hello from Demo Plugin!</h1><p>This page was generated by the community plugin via GenerateRoutes hook.</p><p><a href="/">← Back to home</a></p></div>',
        },
      ],
    };
  },

  // Log each completed page.
  AfterPage(ctx, options, krate) {
    // console.log("[demo] AfterPage: " + ctx.page + " (outName=" + ctx.outName + ")");
    return {};
  },

  // Write a stats JSON file summarizing the build.
  AfterBuild(ctx, options, krate) {
    const pages = (ctx.pages || []).map((p) => ({
      page: p.page,
      outName: p.outName,
      hasJS: p.hasJS,
    }));
    const stats = {
      plugin: "krate-plugin-demo",
      totalPages: pages.length,
      hasCSS: Boolean(ctx.css),
      pages,
    };
    return {
      files: [{ path: "demo-stats.json", content: JSON.stringify(stats, null, 2) }],
    };
  },
};

// Factory used from krate.config.ts: `demoPlugin({ greeting: '...' })`.
export default function demoPlugin(options) {
  return {
    name: "demo",
    order: 10,
    // Point back at this file so the compiler can bundle it. In the Node/tsx
    // config bootstrap this is the real file:// URL; inside the esbuild IIFE
    // (QuickJS) it's empty, which is fine — the compiler already resolved it.
    module: typeof import.meta !== "undefined" && import.meta.url ? import.meta.url : "",
    options: options || {},
  };
}
